apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.example.io
spec:
  # This will cause a violation in newer Kubernetes versions
  preserveUnknownFields: true  
  group: example.io
  names:
    kind: Example
    plural: examples
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema: {}  # Empty schema will also cause violations